# Generated by Django 4.0.3 on 2022-10-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birthdate_alter_user_email_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='describe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='not_twf_exp',
            field=models.TextField(blank=True),
        ),
    ]
