# Generated by Django 4.0.3 on 2022-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='liveplace',
        ),
    ]
