# Generated by Django 4.0.3 on 2022-10-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_describe_alter_user_not_twf_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='describe',
            new_name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
