# Generated by Django 4.0.3 on 2022-10-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_politics_and_processing',
            field=models.BooleanField(default=False),
        ),
    ]
