# Generated by Django 4.0.3 on 2022-11-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('open_time', models.CharField(blank=True, max_length=20)),
                ('close_time', models.CharField(blank=True, max_length=20)),
                ('kitchen_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='socials_thumnails')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('social', models.CharField(blank=True, max_length=20)),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='where_to_go.place')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='where_to_go.socialthumbnail')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='where_to_go.placecategory'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places_images')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where_to_go.place')),
            ],
        ),
    ]
