# Generated by Django 4.0.3 on 2022-11-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('where_to_go', '0004_placearticle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='placearticle',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
    ]
