# Generated by Django 4.0.3 on 2022-11-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0005_placearticle_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PlaceImage',
        ),
    ]
